### PR TITLE
fix(toolbar): make "Thumbs", "Tags", "Zen mode" functions work as default composer

### PR DESCRIPTION
**Pull request by hothetong**
These changes make some toolbar items workable.

### CODE REVIEW

**Comment by julianlam** [comment]
@hothetong You are amazing :trophy:

**Comment by julianlam** [comment]
I was reviewing this PR and was about to change some formatting (to use a `switch..case` instead of sequential ifs with early returns), when I realized that I was passing the quill object in the `.apply()` call instead of `data.postContainer`.

**Why**, I couldn't tell you. It might've been that I wanted to pass in the quill object to do something with a particular toolbar option, but I can't find any references that call it.

It could be I passed it in so that I might _in the future_ use it...

Either way, the core handlers in composer-default expect the post container to be `this`, so I've updated it in 3b4f154 to reflect that.

Appreciate the work nonetheless, and it helped me see the problem :smile:

**Comment by julianlam** [comment]
If you do find a toolbar item that expects `this` to be the quill object, please let me know...

The fix is pretty simple... replace `this` with `this.find('.ql-container').data('quill')`.

**Comment by hothetong** [comment]
> The fix is pretty simple... replace `this` with `this.find('.ql-container').data('quill')`.

Yes, the problem is as simple as that 😄

> Either way, the core handlers in composer-default expect the post container to be `this`, so I've updated it in [3b4f154](https://github.com/NodeBB/nodebb-plugin-composer-quill/commit/3b4f1549b155ddbf1007fdbd39f3ed672d310108) to reflect that.

On my first try, I updated it to 3b4f154, but a toolbar item (added by another plugin) didn't work.

I thought it expected `this` to be quill object. Therefore, I changed my code to sequential ifs with early returns (`switch..case` is much better) so that my changes won't break something.

In this case, it was possible I accidentally tested my first-time changes on a reply post while that plugin only works on the main one. My fault. LOL

3b4f154 seem to be good. But except for `this` problem, there are some more things in my commit. It's my fault (again 😞 ) when not explaining my changes. Please review these too.

- [Add attribute `data-format="thumbs"`](https://github.com/NodeBB/nodebb-plugin-composer-quill/pull/314/commits/b981f1f08517e1c5a3775b254659fe72b8ccaa33#diff-838a2e621aca294bb3a70788ec48583b4696916e48332358815db82fea494a81R289) and [CSS for `.ql-thumbs`](https://github.com/NodeBB/nodebb-plugin-composer-quill/pull/314/commits/b981f1f08517e1c5a3775b254659fe72b8ccaa33#diff-78d4006bb572ac04d17a478950a31aa55f5d5d9f3a1ee3c571030bb7f8e7f779R32-R48) to show thumb count on the "thumb" item on toolbar

- Conditionally push toolbar items to `group` to show/hide them ("thumb" on [`config.allowTopicsThumbnail` condition](https://github.com/NodeBB/nodebb-plugin-composer-quill/pull/314/commits/b981f1f08517e1c5a3775b254659fe72b8ccaa33#diff-838a2e621aca294bb3a70788ec48583b4696916e48332358815db82fea494a81R411) and other toolbar items on [`option.visibility` condition](https://github.com/NodeBB/nodebb-plugin-composer-quill/pull/314/commits/b981f1f08517e1c5a3775b254659fe72b8ccaa33#diff-838a2e621aca294bb3a70788ec48583b4696916e48332358815db82fea494a81R418) ). Honestly, I'm not sure about these conditions, so correct them if they're wrong.

**Comment by hothetong** [comment]
@julianlam Just because I can't help but wonder why did you choose Quill to develop a WYSIWYG composer for NodeBB over others, such as CKEditor or TinyMCE?

The last two are the more popular, user-friendly and feature-rich editors, aren't they? Is there any technical reason like integration, expandable or anything else behind this choice?

I'm new to NodeBB and am learning what I can do with its `hooks`. Please be kind to me 😃

**Comment by julianlam** [comment]
I think CKEditor or TinyMCE have integration issues.. they're also quite opinionated in terms of design, so that causes issues related to theming, etc.

I wanted something lightweight that was also quite powerful... Quill seemed to fit the bill. I like the way it looks, and it seems fairly extendable.

The API backend is indeed a little hairy, however, so who knows, I might change my mind yet again... the other day I discovered [TipTap](https://tiptap.dev/introduction/) which looks quite nice too...!

**Pull request closed without merging**
